# Makefile for Aiksaurus.exe

all:
	@cd base
	@-$(MAKE) /NOLOGO -f MakefileLIB.msc $@
	@cd ../win/src
	@-$(MAKE) /NOLOGO -f Makefile.msc $@

clean:
	@cd base
	@-$(MAKE) /NOLOGO -f MakefileLIB.msc $@
	@cd ../win/src
	@-$(MAKE) /NOLOGO -f Makefile.msc $@

