/*
 * Aiksaurus - An open source thesaurus library
 * Copyright (C) 2001 by Jared Davis
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 */

/*
 * This file is automatically generated by the MkOffsetTable 
 * program.  It should not be necessary to modify this file by 
 * hand.  Please see the MkOffsetTable program for more info.
 *
 */


const int AiksaurusImpl::MeaningsFile::s_offsetModulus = 10;

const int AiksaurusImpl::MeaningsFile::s_offsetData[] = 
{
	0,	 // 0 lines
	414,	 // 10 lines
	944,	 // 20 lines
	1624,	 // 30 lines
	2072,	 // 40 lines
	2824,	 // 50 lines
	3950,	 // 60 lines
	4574,	 // 70 lines
	5114,	 // 80 lines
	5714,	 // 90 lines
	6342,	 // 100 lines
	6844,	 // 110 lines
	7170,	 // 120 lines
	7698,	 // 130 lines
	8352,	 // 140 lines
	9118,	 // 150 lines
	9622,	 // 160 lines
	10240,	 // 170 lines
	11200,	 // 180 lines
	11930,	 // 190 lines
	12478,	 // 200 lines
	13050,	 // 210 lines
	13466,	 // 220 lines
	14254,	 // 230 lines
	14964,	 // 240 lines
	15664,	 // 250 lines
	16264,	 // 260 lines
	16944,	 // 270 lines
	17640,	 // 280 lines
	18322,	 // 290 lines
	18838,	 // 300 lines
	19322,	 // 310 lines
	19958,	 // 320 lines
	20464,	 // 330 lines
	21010,	 // 340 lines
	21648,	 // 350 lines
	22278,	 // 360 lines
	23008,	 // 370 lines
	23694,	 // 380 lines
	24262,	 // 390 lines
	24800,	 // 400 lines
	25332,	 // 410 lines
	25894,	 // 420 lines
	26436,	 // 430 lines
	26944,	 // 440 lines
	27404,	 // 450 lines
	27858,	 // 460 lines
	28364,	 // 470 lines
	28784,	 // 480 lines
	29322,	 // 490 lines
	29852,	 // 500 lines
	30446,	 // 510 lines
	30864,	 // 520 lines
	31398,	 // 530 lines
	31836,	 // 540 lines
	32364,	 // 550 lines
	32834,	 // 560 lines
	33258,	 // 570 lines
	33746,	 // 580 lines
	34254,	 // 590 lines
	34786,	 // 600 lines
	35296,	 // 610 lines
	35806,	 // 620 lines
	36548,	 // 630 lines
	36938,	 // 640 lines
	37356,	 // 650 lines
	37800,	 // 660 lines
	38192,	 // 670 lines
	38668,	 // 680 lines
	39262,	 // 690 lines
	39912,	 // 700 lines
	40630,	 // 710 lines
	41294,	 // 720 lines
	41756,	 // 730 lines
	42420,	 // 740 lines
	42916,	 // 750 lines
	43336,	 // 760 lines
	43752,	 // 770 lines
	44204,	 // 780 lines
	44734,	 // 790 lines
	45176,	 // 800 lines
	45528,	 // 810 lines
	45984,	 // 820 lines
	46480,	 // 830 lines
	47048,	 // 840 lines
	47590,	 // 850 lines
	48062,	 // 860 lines
	48582,	 // 870 lines
	49014,	 // 880 lines
	49534,	 // 890 lines
	50056,	 // 900 lines
	50464,	 // 910 lines
	50960,	 // 920 lines
	51428,	 // 930 lines
	52004,	 // 940 lines
	52578,	 // 950 lines
	53144,	 // 960 lines
	53600,	 // 970 lines
	54030,	 // 980 lines
	54516,	 // 990 lines
	54870,	 // 1000 lines
	55242,	 // 1010 lines
	55652,	 // 1020 lines
	56148,	 // 1030 lines
	56642,	 // 1040 lines
	57220,	 // 1050 lines
	57656,	 // 1060 lines
	58294,	 // 1070 lines
	58688,	 // 1080 lines
	59050,	 // 1090 lines
	59358,	 // 1100 lines
	59792,	 // 1110 lines
	60240,	 // 1120 lines
	60784,	 // 1130 lines
	61162,	 // 1140 lines
	61552,	 // 1150 lines
	61946,	 // 1160 lines
	62392,	 // 1170 lines
	62738,	 // 1180 lines
	63098,	 // 1190 lines
	63476,	 // 1200 lines
	63846,	 // 1210 lines
	64246,	 // 1220 lines
	64642,	 // 1230 lines
	65086,	 // 1240 lines
	65470,	 // 1250 lines
	65946,	 // 1260 lines
	66330,	 // 1270 lines
	66690,	 // 1280 lines
	67160,	 // 1290 lines
	67602,	 // 1300 lines
	68064,	 // 1310 lines
	68548,	 // 1320 lines
	68892,	 // 1330 lines
	69310,	 // 1340 lines
	69678,	 // 1350 lines
	70100,	 // 1360 lines
	70478,	 // 1370 lines
	70778,	 // 1380 lines
	71230,	 // 1390 lines
	71592,	 // 1400 lines
	71938,	 // 1410 lines
	72332,	 // 1420 lines
	72686,	 // 1430 lines
	73134,	 // 1440 lines
	73500,	 // 1450 lines
	73876,	 // 1460 lines
	74262,	 // 1470 lines
	74618,	 // 1480 lines
	75022,	 // 1490 lines
	75396,	 // 1500 lines
	75778,	 // 1510 lines
	76198,	 // 1520 lines
	76618,	 // 1530 lines
	77168,	 // 1540 lines
	77578,	 // 1550 lines
	77998,	 // 1560 lines
	78380,	 // 1570 lines
	78984,	 // 1580 lines
	79292,	 // 1590 lines
	79592,	 // 1600 lines
	80064,	 // 1610 lines
	80546,	 // 1620 lines
	80854,	 // 1630 lines
	81248,	 // 1640 lines
	81616,	 // 1650 lines
	82020,	 // 1660 lines
	82352,	 // 1670 lines
	82630,	 // 1680 lines
	83068,	 // 1690 lines
	83442,	 // 1700 lines
	83812,	 // 1710 lines
	84200,	 // 1720 lines
	84630,	 // 1730 lines
	85048,	 // 1740 lines
	85434,	 // 1750 lines
	85782,	 // 1760 lines
	86110,	 // 1770 lines
	86490,	 // 1780 lines
	86886,	 // 1790 lines
	87258,	 // 1800 lines
	87564,	 // 1810 lines
	87858,	 // 1820 lines
	88174,	 // 1830 lines
	88448,	 // 1840 lines
	88764,	 // 1850 lines
	89130,	 // 1860 lines
	89478,	 // 1870 lines
	89818,	 // 1880 lines
	90170,	 // 1890 lines
	90552,	 // 1900 lines
	90880,	 // 1910 lines
	91204,	 // 1920 lines
	91518,	 // 1930 lines
	91932,	 // 1940 lines
	92310,	 // 1950 lines
	92598,	 // 1960 lines
	92914,	 // 1970 lines
	93250,	 // 1980 lines
	93664,	 // 1990 lines
	93960,	 // 2000 lines
	94346,	 // 2010 lines
	94666,	 // 2020 lines
	94984,	 // 2030 lines
	95298,	 // 2040 lines
	95612,	 // 2050 lines
	95962,	 // 2060 lines
	96324,	 // 2070 lines
	96584,	 // 2080 lines
	96950,	 // 2090 lines
	97236,	 // 2100 lines
	97518,	 // 2110 lines
	97832,	 // 2120 lines
	98088,	 // 2130 lines
	98386,	 // 2140 lines
	98662,	 // 2150 lines
	98960,	 // 2160 lines
	99236,	 // 2170 lines
	99626,	 // 2180 lines
	99962,	 // 2190 lines
	100264,	 // 2200 lines
	100590,	 // 2210 lines
	100872,	 // 2220 lines
	101184,	 // 2230 lines
	101470,	 // 2240 lines
	101762,	 // 2250 lines
	102038,	 // 2260 lines
	102416,	 // 2270 lines
	102932,	 // 2280 lines
	103364,	 // 2290 lines
	103754,	 // 2300 lines
	104252,	 // 2310 lines
	104578,	 // 2320 lines
	105006,	 // 2330 lines
	105430,	 // 2340 lines
	105862,	 // 2350 lines
	106242,	 // 2360 lines
	106650,	 // 2370 lines
	107040,	 // 2380 lines
	107408,	 // 2390 lines
	107780,	 // 2400 lines
	108096,	 // 2410 lines
	108472,	 // 2420 lines
	108810,	 // 2430 lines
	109182,	 // 2440 lines
	109580,	 // 2450 lines
	109900,	 // 2460 lines
	110226,	 // 2470 lines
	110554,	 // 2480 lines
	110882,	 // 2490 lines
	111206,	 // 2500 lines
	111538,	 // 2510 lines
	111916,	 // 2520 lines
	112250,	 // 2530 lines
	112592,	 // 2540 lines
	112954,	 // 2550 lines
	113250,	 // 2560 lines
	113576,	 // 2570 lines
	113938,	 // 2580 lines
	114288,	 // 2590 lines
	114560,	 // 2600 lines
	114916,	 // 2610 lines
	115300,	 // 2620 lines
};

const int AiksaurusImpl::MeaningsFile::s_dataMaxLineLength = 368;


// total bytes read: 115330
